name: para

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  para:
    runs-on: ubuntu-latest
    timeout-minutes: 340  # 5 hours 40 minutes

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set hostname to para
        run: sudo hostnamectl set-hostname para

      - name: Download VPS backup (if any)
        uses: actions/download-artifact@v4
        with:
          name: vps-backup
          path: ./backup
        continue-on-error: true

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y curl unzip sudo net-tools neofetch
      - name: Install Tailscale official script
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
      - name: Restore backup files
        run: |
          if [ -f ./backup/backup.zip ]; then
            unzip -o ./backup/backup.zip -d /opt/vps-backup
          else
            echo "No backup found, starting fresh"
          fi
      - name: Restore Tailscale state
        run: |
          if [ -f /opt/vps-backup/data/tailscaled.state ]; then
            sudo mkdir -p /var/lib/tailscale
            sudo cp /opt/vps-backup/data/tailscaled.state /var/lib/tailscale/tailscaled.state
            sudo chmod 600 /var/lib/tailscale/tailscaled.state
          fi
      - name: Start Tailscale
        run: |
          sudo tailscaled &
          sleep 8
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname=para || echo "Tailscale already up"
      - name: Create user para with sudo
        run: |
          if ! id -u para >/dev/null 2>&1; then
            sudo useradd -m -s /bin/bash para
            echo "para:para" | sudo chpasswd
            sudo usermod -aG sudo para
            echo "para ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/para
          fi
      - name: Start SSHX session as para
        run: |
          sudo -u para -H bash -c '
            set -x
            cd /home/para
            echo "💻 Connect via Termius/SSH client:"
            echo ""
            echo "📡 Fetching Tailscale IP..."
            TS_IP=$(tailscale ip -4 2>/dev/null | head -n 1)
            if [ -n "$TS_IP" ]; then
              echo "🔑 Tailscale IP: $TS_IP"
              echo "👉 Connect with: ssh para@$TS_IP"
              echo "👤 Username: para"
              echo "🔑 Password: para"
            else
              echo "⚠️ No Tailscale IP found. Maybe Tailscale isn’t fully connected."
            fi

            echo ""
            echo "⚡ Starting SSHX session..."
            curl -sSf https://sshx.io/get | sh -s run
            which sshx
            sshx --version

            # Start sshx in background
            sshx -t -o StrictHostKeyChecking=no &
            SSHX_PID=$!

            # Keep alive loop for 340 minutes
            end=$((SECONDS + 340*60))
            while [ $SECONDS -lt $end ]; do
              if ! kill -0 $SSHX_PID 2>/dev/null; then
                echo "❌ SSHX process exited."
                break
              fi
              echo "💤 Still alive... $(date)"
              sleep 60
            done

            set +x
          '
      - name: Backup VPS data
        run: |
          sudo mkdir -p /opt/vps-backup/data
          sudo cp /var/lib/tailscale/tailscaled.state /opt/vps-backup/data/
          sudo chown -R $USER:$USER /opt/vps-backup
          zip -r backup.zip /opt/vps-backup
      - name: Upload VPS backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: vps-backup
          path: backup.zip
